---
title: CA2124:在外部 try 块中包装易受攻击的 finally 子句
description: 在版本 1.0 和 1.1 的 .NET Framework 中，公共或受保护方法包含 try/catch/finally 块。 finally 块似乎可重置安全状态，并且未包含在 finally 块中。
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
helpviewer_keywords:
- CA2124
- WrapVulnerableFinallyClausesInOuterTry
ms.assetid: 82efd224-9e60-4b88-a0f5-dfabcc49a254
author: mikejo5000
ms.author: mikejo
manager: jmartens
ms.technology: vs-ide-code-analysis
ms.workload:
- multiple
ms.openlocfilehash: 9531f3579fd0ccf83563cb667bca51a6bfc3c4c35d0834e6ffb8340f07dcf606
ms.sourcegitcommit: c72b2f603e1eb3a4157f00926df2e263831ea472
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 08/12/2021
ms.locfileid: "121405859"
---
# <a name="ca2124-wrap-vulnerable-finally-clauses-in-outer-try"></a>CA2124:在外部 try 块中包装易受攻击的 finally 子句

|项|“值”|
|-|-|
|RuleId|CA2124|
|Category|Microsoft.Security|
|重大更改|非中断|

## <a name="cause"></a>原因
在版本 1.0 和 1.1 .NET Framework中，公共或受保护方法包含 `try` / `catch` / `finally` 块。 `finally`块似乎重置安全状态，并且未包含在 `finally` 块中。

> [!NOTE]
> 此规则已被弃用。 有关详细信息，请参阅已 [弃用的规则](fxcop-unported-deprecated-rules.md)。

## <a name="rule-description"></a>规则说明
此规则在面向 `try` / `finally` 1.0 和 1.1 版的代码中查找可能容易受到调用堆栈中恶意异常筛选器.NET Framework的块。 如果 try 块中发生敏感操作（如模拟）并引发异常，则筛选器可以在块之前 `finally` 执行。 对于模拟示例，这意味着筛选器将作为模拟用户执行。 筛选器目前只能在 Visual Basic。

> [!NOTE]
> 在 2.0 及更高版本的 .NET Framework 中，如果重置直接在包含异常块的方法中发生，则运行时会自动保护块免受恶意异常 `try` / `catch` /  `finally` 筛选器的攻击。

## <a name="how-to-fix-violations"></a>如何解决冲突
将解包的 `try` / `finally` 放在外部 try 块中。 请参阅以下第二个示例。 这会强制 `finally` 在筛选代码之前执行 。

## <a name="when-to-suppress-warnings"></a>何时禁止显示警告
不禁止显示此规则发出的警告。

## <a name="pseudo-code-example"></a>伪代码示例

### <a name="description"></a>说明

下面伪代码说明此规则检测到的模式。

```csharp
try {
   // Do some work.
   Impersonator imp = new Impersonator("John Doe");
   imp.AddToCreditCardBalance(100);
}
finally {
   // Reset security state.
   imp.Revert();
}
```

以下伪代码显示了可用于保护代码并满足此规则的模式。

```csharp
try {
     try {
        // Do some work.
     }
     finally {
        // Reset security state.
     }
}
catch()
{
    throw;
}
```
